name         'rfletcher-aws_cli'
version      '0.1.0'
license      'MIT License'
summary      'A puppet module for AWS command line tools'
description  'Install or remove AWS command line tools'
project_page 'https://github.com/rfletcher/puppet-aws_cli'
source       'https://github.com/rfletcher/puppet-aws_cli'

dependency   'stankevich/python',  '>= 1.7.2'
dependency   'puppetlabs/inifile', '>= 1.0.0'
dependency   'puppetlabs/stdlib',  '>= 4.1.0'
